using PersonnelTransportAutomation.Samples;
using Xunit;

namespace PersonnelTransportAutomation.EntityFrameworkCore.Applications;

[Collection(PersonnelTransportAutomationTestConsts.CollectionDefinitionName)]
public class EfCoreSampleAppServiceTests : SampleAppServiceTests<PersonnelTransportAutomationEntityFrameworkCoreTestModule>
{

}
