// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.EntityFrameworkCore;

#nullable disable

namespace Persistence.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DBO")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<string>("TenantCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Explanation");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Status");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.HasKey("TenantCode", "Id");

                    b.ToTable("PRODUCT", "DBO");

                    b.HasData(
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("1829ae59-47ff-48c1-9cf0-7a709e48e048"),
                            Category = "Category1",
                            Code = "Code1",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8483),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation1",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name1",
                            Price = 1m,
                            Status = "Active",
                            Stock = 1
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("d005f059-c7f7-468e-8746-21bfd3b1bf2c"),
                            Category = "Category2",
                            Code = "Code2",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8495),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation2",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name2",
                            Price = 2m,
                            Status = "Active",
                            Stock = 2
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("94645c20-ff23-432f-9b39-d836bd738839"),
                            Category = "Category3",
                            Code = "Code3",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8500),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation3",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name3",
                            Price = 3m,
                            Status = "Active",
                            Stock = 3
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("34c56059-df6b-4d78-8d19-bab3c537a2e8"),
                            Category = "Category4",
                            Code = "Code4",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8515),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation4",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name4",
                            Price = 4m,
                            Status = "Active",
                            Stock = 4
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("ebf2d5d9-97b8-4f7e-ae2b-986470751063"),
                            Category = "Category5",
                            Code = "Code5",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8519),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation5",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name5",
                            Price = 5m,
                            Status = "Active",
                            Stock = 5
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("45b79499-3953-425e-bfa5-d01bd5a70435"),
                            Category = "Category6",
                            Code = "Code6",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8526),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation6",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name6",
                            Price = 6m,
                            Status = "Active",
                            Stock = 6
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("abeaf34f-6763-4577-b07a-4d793d61f58e"),
                            Category = "Category7",
                            Code = "Code7",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8531),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation7",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name7",
                            Price = 7m,
                            Status = "Active",
                            Stock = 7
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("d93a4754-e0ef-4a92-aa4c-7da6d8378733"),
                            Category = "Category8",
                            Code = "Code8",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8535),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation8",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name8",
                            Price = 8m,
                            Status = "Active",
                            Stock = 8
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("8b56b056-3ad6-40f2-922e-f6ea2196316f"),
                            Category = "Category9",
                            Code = "Code9",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8539),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation9",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name9",
                            Price = 9m,
                            Status = "Active",
                            Stock = 9
                        },
                        new
                        {
                            TenantCode = "DEFAULT",
                            Id = new Guid("fc8efe88-eb3f-4e5d-b4b8-97ac3ff5fb45"),
                            Category = "Category10",
                            Code = "Code10",
                            CreatedAt = new DateTime(2023, 8, 27, 11, 54, 26, 197, DateTimeKind.Utc).AddTicks(8545),
                            CreatedBy = "DEFAULT",
                            Explanation = "Explanation10",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = "",
                            Name = "Name10",
                            Price = 10m,
                            Status = "Active",
                            Stock = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
