using PersonnelTransportAutomation.EntityFrameworkCore;
using Xunit;

namespace PersonnelTransportAutomation.EntityFrameworkCore;

public class PersonnelTransportAutomationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<PersonnelTransportAutomationEntityFrameworkCoreFixture>
{

}
