using Volo.Abp;

namespace PersonnelTransportAutomation.EntityFrameworkCore;

public abstract class PersonnelTransportAutomationEntityFrameworkCoreTestBase : PersonnelTransportAutomationTestBase<PersonnelTransportAutomationEntityFrameworkCoreTestModule>
{

}
