using Xunit;

namespace PersonelTransportAutomation.EntityFrameworkCore;

[CollectionDefinition(PersonelTransportAutomationTestConsts.CollectionDefinitionName)]
public class PersonelTransportAutomationEntityFrameworkCoreCollection : ICollectionFixture<PersonelTransportAutomationEntityFrameworkCoreFixture>
{

}
