using Volo.Abp;

namespace PersonelTransportAutomation.EntityFrameworkCore;

public abstract class PersonelTransportAutomationEntityFrameworkCoreTestBase : PersonelTransportAutomationTestBase<PersonelTransportAutomationEntityFrameworkCoreTestModule>
{

}
