"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { useContext, useState } from "react";
import { Layout, Menu, Space, theme } from "antd";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { AuthContext, AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Service Automation",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const { Header, Content, Footer, Sider } = Layout;
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  const context = useContext(AuthContext);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Layout>
            {context?.isAuthenticated ? <Sider>Sider</Sider> : "no sider"}
            <Layout>
              <Header>Header</Header>
              <Content>{children}</Content>
              <Footer>Footer</Footer>
            </Layout>
          </Layout>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
